config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#index'

  resources :users, only: [:new, :create]

  resources :plants, only: [:index]

  resources :user_sessions, only: [:create, :destroy]

  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in

  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/etl_meta.rb
class EtlMeta < ApplicationRecord
  belongs_to :etl_record, polymorphic: true
end

app/models/plant.rb
class Plant < ApplicationRecord
  has_one :etl_meta, as: :etl_record
  months = [:january, :february, :march, :april, :may, :june, :july, :august, :september, :october, :november, :december]
  flag :fruit_months, months
  flag :growth_months, months
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_authentic do |c|
    c.crypto_provider = Authlogic::CryptoProviders::Sha512
  end
  # Validate email, login, and password as you see fit.
  #
  # Authlogic < 5 added these validation for you, making them a little awkward
  # to change. In 4.4.0, those automatic validations were deprecated. See
  # https://github.com/binarylogic/authlogic/blob/master/doc/use_normal_rails_validation.md
  validates :email,
            format: {
              with: /@/,
              message: 'should look like an email address.'
            },
            length: { maximum: 100 },
            uniqueness: {
              case_sensitive: false,
              if: :will_save_change_to_email?
            }

  validates :password,
            confirmation: { if: :require_password? },
            length: {
              minimum: 8,
              if: :require_password?
            }
  validates :password_confirmation,
            length: {
              minimum: 8,
              if: :require_password?
            }
  def deliver_password_reset_instructions!
    reset_perishable_token!
    PasswordResetMailer.reset_email(self).deliver_now
  end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def current_user_session
    return @current_user_session if defined?(@current_user_session)

    @current_user_session = UserSession.find
  end

  def current_user
    return @current_user if defined?(@current_user)

    @current_user = current_user_session&.user
  end

  helper_method :current_user_session, :current_user
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index; end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new; end

  def create
    @user = User.find_by_email(params[:email])
    if @user
      @user.deliver_password_reset_instructions!
      flash[:success] = 'Instructions to reset your password have been emailed to you.'
      redirect_to root_path
    else
      flash[:warning] = 'No user was found with that email address'
      render :new
    end
  end

  def edit
    @user = User.find_by(perishable_token: params[:id])
  end

  def update
    @user = User.find_by(perishable_token: params[:id])
    if @user.update_attributes(password_reset_params)
      flash[:success] = 'Password successfully updated!'
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def password_reset_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  def index
    @plants = Plant.all
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(user_session_params.to_h)
    if @user_session.save
      flash[:success] = 'Welcome back!'
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    current_user_session.destroy
    flash[:success] = 'Goodbye!'
    redirect_to root_path
  end

  private

  def user_session_params
    params.require(:user_session).permit(:email, :password, :remember_me)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(users_params)
    if @user.save
      flash[:success] = 'Account registered!'
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def users_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
  def display(value, type:)
    case type
    when :nilable
      display_nilable(value)
    when :range
      display_range(value)
    when :array
      display_array(value)
    when :boolean
      display_boolean(value)
    end
  end

  def display_nilable(value)
    value || 'unknown'
  end

  def display_boolean(value)
    value ? 'yes' : 'no'
  end

  def display_array(value)
    if value.nil? || value == []
      nil_placeholder
    else
      render 'shared/array', array: value
    end
  end

  def display_range(value)
    (lower, upper) = value
    if lower.nil? && upper.nil?
      nil_placeholder
    elsif lower.nil?
      "less than #{upper}"
    elsif upper.nil?
      "more than #{lower}"
    else
      "#{lower} - #{upper}"
    end
  end

  def preview_card(plant)
    image_url = plant.image_url || 'plant_not_found.png'
    title = plant.common_name
    details_text = 'Details'
    details_url = plants_path(plant)
    render 'shared/card', image_url: image_url, title: title, details_text: details_text, details_url: details_url
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GardenHelper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <%= link_to 'Garden Helper', root_path, class: 'navbar-brand' %>
        </div>
        <div id="navbar">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Home', root_path %></li>
          </ul>
          <ul class="nav navbar-nav pull-right">
            <% if current_user %>
              <li><span><%= current_user.email %></span></li>
              <li><%= link_to 'Sign Out', sign_out_path, method: :delete %></li>
            <% else %>
              <li><%= link_to 'Sign In', sign_in_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <%= value %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<% if current_user %>
  <div class="page-header"><h1>Welcome back!</h1></div>

  <h2>Some info about you...</h2>

  <div class="well well-lg">
    <ul>
      <li>Login count: <%= current_user.login_count %></li>
      <li>Failed login count: <%= current_user.failed_login_count %></li>
      <li>Last request: <%= current_user.last_request_at %></li>
      <li>Current login at: <%= current_user.current_login_at %></li>
      <li>Last login at: <%= current_user.last_login_at %></li>
      <li>Current login IP: <%= current_user.current_login_ip %></li>
      <li>Last login IP: <%= current_user.last_login_ip %></li>
    </ul>
  </div>
<% else %>
  <div class="jumbotron">
    <div class="container">
      <h1>Welcome!</h1>
      <p>Sign up to get started.</p>
      <p>
        <%= link_to new_user_path, class: 'btn btn-primary btn-lg' do %>
          Sign Up &raquo;
        <% end %>
      </p>
    </div>
  </div>
<% end %>

app/views/plants/_preview.html.erb
<%# render a plant as a card to be included in another page %>
<div class="card" style="width: 18rem">
  <%= image_tag plant.image_url || "plant_not_found.png", size:"180x180", class: "Card" %>
  <div class="card-body">
    <h5 class="card-title"><%= plant.common_name %></h5>
    <%= link_to 'Details', plants_path(plant), class: 'btn btn-primary' %>
  </div>
</div>

app/views/plants/index.html.erb
<% @plants.each do |plant| %>
  <%= render 'plants/preview', plant: plant %>
<% end %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="panel panel-warning errors">
    <div class="panel-heading">
      <h5><i class="glyphicon glyphicon-exclamation-sign"></i> Found errors while saving</h5>
    </div>

    <ul class="panel-body">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/user_sessions/new.html.erb
<div class="page-header"><h1>Sign In</h1></div>

<%= form_for @user_session do |f| %>
  <%= render 'shared/errors', object: @user_session %>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label 'Remember Me' %>
    <%= f.check_box :remember_me, class: 'checkbox-inline' %>
  </div>

  <%= f.submit 'Sign In', class: 'btn btn-primary btn-lg' %>
  <br/><br/>
  <%= link_to 'Forgot your password?', new_password_reset_path, class: 'btn btn-sm btn-default' %>
<% end %>

app/views/users/new.html.erb
<div class="page-header"><h1>Register</h1></div>

<%= form_for @user do |f| %>
  <%= render 'shared/errors', object: @user %>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>

  <%= f.submit 'Register', class: 'btn btn-primary btn-lg' %>
<% end %>